server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/penaltydb
    username: pdbs
    password: 1
    hikari:
      maximumPoolSize: 10

localization:
  statenumbervalidator: rus